# Generated by Django 5.2.5 on 2025-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailopt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailopt',
            name='opt_attempt',
            field=models.CharField(default=0),
        ),
    ]
