# Generated by Django 5.2.5 on 2025-08-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailopt_opt_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailopt',
            name='opt_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
